apiVersion: v1
kind: Template
metadata:
  name: "tinyproxy"
message: "tinyproxy"
objects:

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: tinyproxy
  spec:
    output:
      to:
        kind: "DockerImage"
        name: "image-registry.openshift-image-registry.svc:5000/proxy/tinyproxy:example"
    source:
      git:
        uri: https://github.com/samugi/openshift-tinyproxy.git
      type: "Dockerfile"
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: openshift/Dockerfile

- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: tinyproxy
    namespace: proxy
  spec:
    selector:
      app: tinyproxy
    replicas: 1
    template:
      metadata:
        labels:
          app: tinyproxy
      spec:
        containers:
          - name: tinyproxy
            image: >-
              image-registry.openshift-image-registry.svc:5000/proxy/tinyproxy:example
            ports:
              - containerPort: 8888

- apiVersion: v1
  kind: Service
  metadata:
    name: tinyproxy
    namespace: proxy
  spec:
    selector:
      app: tinyproxy
    ports:
      - protocol: TCP
        port: 8888
        targetPort: 8888

